// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcsg3cF_uvZO7IGQ9lHZWRZbRzy0sxiow',
    appId: '1:903834040298:web:12a14530b34e83250b2493',
    messagingSenderId: '903834040298',
    projectId: 'feierabendbierchen-14824',
    authDomain: 'feierabendbierchen-14824.firebaseapp.com',
    storageBucket: 'feierabendbierchen-14824.firebasestorage.app',
    measurementId: 'G-9NJV270CRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARpQoM1DQfz9BX2h0tRvv4uRm4NOZCshQ',
    appId: '1:903834040298:android:5efa655417b661620b2493',
    messagingSenderId: '903834040298',
    projectId: 'feierabendbierchen-14824',
    storageBucket: 'feierabendbierchen-14824.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH6xtOpReyRqijIt14M5DkA-ahomph6bc',
    appId: '1:903834040298:ios:21fda16aff902bf60b2493',
    messagingSenderId: '903834040298',
    projectId: 'feierabendbierchen-14824',
    storageBucket: 'feierabendbierchen-14824.firebasestorage.app',
    iosClientId: '903834040298-9rmg534ocim9jhn97p3t0s2dscg8tqjj.apps.googleusercontent.com',
    iosBundleId: 'com.example.feierabendbierchenFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH6xtOpReyRqijIt14M5DkA-ahomph6bc',
    appId: '1:903834040298:ios:21fda16aff902bf60b2493',
    messagingSenderId: '903834040298',
    projectId: 'feierabendbierchen-14824',
    storageBucket: 'feierabendbierchen-14824.firebasestorage.app',
    iosClientId: '903834040298-9rmg534ocim9jhn97p3t0s2dscg8tqjj.apps.googleusercontent.com',
    iosBundleId: 'com.example.feierabendbierchenFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcsg3cF_uvZO7IGQ9lHZWRZbRzy0sxiow',
    appId: '1:903834040298:web:f75f7292794cdeab0b2493',
    messagingSenderId: '903834040298',
    projectId: 'feierabendbierchen-14824',
    authDomain: 'feierabendbierchen-14824.firebaseapp.com',
    storageBucket: 'feierabendbierchen-14824.firebasestorage.app',
    measurementId: 'G-0R8FLEX0G0',
  );

}